"""add db

Revision ID: 7cc48d527fe8
Revises: 
Create Date: 2021-06-20 19:34:07.129793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cc48d527fe8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gamequest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quest', sa.Text(), nullable=True),
    sa.Column('correct', sa.String(length=64), nullable=True),
    sa.Column('wrong1', sa.String(length=64), nullable=True),
    sa.Column('wrong2', sa.String(length=64), nullable=True),
    sa.Column('wrong3', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gamequest_quest'), 'gamequest', ['quest'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('surname', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('point', sa.Integer(), nullable=True),
    sa.Column('login', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_login'), 'users', ['login'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_login'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_gamequest_quest'), table_name='gamequest')
    op.drop_table('gamequest')
    # ### end Alembic commands ###
